### ISSUE TITLE
A question about this library

### ISSUE THREAD

**Issue by bigmeech** [wltsmrz/node-prosody#1]
So looking at the code, you seem to be administering prosody server from node using http requests(Which is cool). But what i dont get is why you have to send messages via http. You wouldnt exactly call that "realtime" would you?

**Comment by wltsmrz** [comment]
> But what i dont get is why you have to send messages via http

You have to send messages via HTTP if you use node-prosody, because node-prosody uses HTTP, which you already mentioned.

> You wouldnt exactly call that "realtime" would you?

Whether or not it's "real time" would depend on your definition of "real time" and how you use node-prosody. The best alternative for administering Prosody programmatically might be `mod_admin_adhoc`, but features are limited.

I can't find anything clearly objective to address in this issue, so I will close it. Hopefully this was helpful in some way..
